# Generated by Django 5.0.1 on 2026-03-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_category_alter_assetmovement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmovement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.assetcategory'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='expected_return_time',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_checked_out',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
